Autenticacion de usuarios
alkemyTech/OT244-Server pull request #11
Opened 2022-07-18 19:47 UTC by mar-romero

2022-07-19 20:59 UTC, maxxCeballos requested changes

2022-07-19 20:59 UTC, maxxCeballos commented on services/authService.js
> +        if(!user.enable){
de donde sale el enable?

2022-07-19 20:59 UTC, maxxCeballos commented on services/authService.js
> +const userService = require('./userService');
userService no esta implementado

2022-07-19 20:59 UTC, maxxCeballos commented on services/authService.js
> +        const token = _encrypt(user.id);
La tarea no dice nada de generar un token

2022-07-25 23:28 UTC, maxxCeballos requested changes

2022-07-25 23:28 UTC, maxxCeballos commented on services/userService.js
> +}
Lo que esta en este archivo no se solicita en el tiket.

2022-07-25 23:28 UTC, maxxCeballos commented on services/authService.js
> +        }
se repite dos veces la misma validacion

2022-07-25 23:28 UTC, maxxCeballos commented on repositories/userRepository.js
> +module.exports = UserRepository;
solo se necesita logica para poder loguear al usuario, no todas las consultas a la base de datos.

2022-07-27 01:59 UTC, maxxCeballos approved these changes

2022-07-27 13:04 UTC, sebasam reviewed
fixing conficts

2022-07-27 13:13 UTC, merged