Feature/sign up user endpoint
alkemyTech/OT244-Server pull request #12
Opened 2022-07-18 20:01 UTC by JAFleitas

description in commits

2022-07-19 20:43 UTC, maxxCeballos commented
No se solicitó eliminar el .env.example

2022-07-19 20:49 UTC, maxxCeballos requested changes

2022-07-19 20:49 UTC, maxxCeballos commented on routes/users.js
> +router.post("/auth/register", bodyFields, validateFields, createUser);
como se accede a esta ruta?

2022-07-19 20:49 UTC, maxxCeballos commented on controllers/user.js
> +    return response.status(404).json({ msg: "An unexpected error occurred" });
El status 404 es cuando no se encontró un recurso. Para este caso seria mas apropiado un 500

2022-07-19 23:26 UTC, JAFleitas commented on routes/users.js
> +router.post("/auth/register", bodyFields, validateFields, createUser);
Hola Maxi, no entiendo tu pregunta, me explicas por favor?

2022-07-19 23:26 UTC, JAFleitas commented on controllers/user.js
> +    return response.status(404).json({ msg: "An unexpected error occurred" });
Gracias por el feedback

2022-07-20 16:50 UTC, maxxCeballos commented on routes/users.js
> +router.post("/auth/register", bodyFields, validateFields, createUser);
Si levantas el servidor y haces un request a esa ruta anda?

2022-07-20 17:13 UTC, JAFleitas commented on routes/users.js
> +router.post("/auth/register", bodyFields, validateFields, createUser);
Ahh no, lo puse dentro del archivo user, es decir que para poder hacer match con la ruta hay pegarle a la ruta user/auth/register
Pensé que como tenía que ver con crear un usuario lo puse en el router de user. Decís que lo migre a una carpeta auth?

2022-07-20 22:13 UTC, JAFleitas commented on routes/users.js
> +router.post("/auth/register", bodyFields, validateFields, createUser);
Ya lo migre Maxi gracias por el feedback

2022-07-23 00:30 UTC, maxxCeballos approved these changes

2022-07-23 01:40 UTC, merged