Feature/create categories
alkemyTech/OT244-Server pull request #15
Opened 2022-07-23 21:39 UTC by JAFleitas

- Se creo el endpoint POST/categories para que el administrador agregue categorias
- Se agregaron las rutas en app.js y se creo el archivo /routes/category.js
- IMPORTANTE : falta crear el modelo y las migraciones de la tabla CATEGORIES

2022-07-25 23:37 UTC, maxxCeballos requested changes

2022-07-25 23:37 UTC, maxxCeballos commented on controllers/category.js
> +    const newCategory = await Category.create({ name });
Si bien se valida como minimo que se envie el field name, que pasa si se envian los campos content e image que tambien pertenecen al modelo de categories? no se estan teniendo en cuenta a la hora de crear el registro

2022-07-25 23:47 UTC, JAFleitas commented on controllers/category.js
> +    const newCategory = await Category.create({ name });
Tenés razón maxi me olvidé de agregarlos en 5 lo fixeo, gracias por el feedback!

2022-07-25 23:53 UTC, JAFleitas commented on controllers/category.js
> +    const newCategory = await Category.create({ name });
Listo Max!!

2022-07-26 00:15 UTC, maxxCeballos approved these changes

2022-07-27 13:21 UTC, merged