middleware/user-autenticate function validateJWT added, verify if tok…
alkemyTech/OT244-Server pull request #19
Opened 2022-07-24 05:01 UTC by sebasam

### Summary

- middlewares/user-autenticate.js and function validateJWT if token belongs to any user.

2022-07-25 23:56 UTC, maxxCeballos requested changes

2022-07-25 23:56 UTC, maxxCeballos commented on middlewares/user-autenticate.js
> +        req.firstName = firstName;
esto no se solicita en el tiket

2022-07-26 00:05 UTC, sebasam commented
### Summary

- User info has been deleted from middleware

2022-07-27 02:08 UTC, maxxCeballos requested changes

2022-07-27 02:08 UTC, maxxCeballos commented on middlewares/user-autenticate.js
> +        jwt.verify(token, process.env.JWT_SECRET);
Seba no me expresé bien, me referia a obtener el user completo del token y agregarlo como atributo de req.

2022-07-27 12:49 UTC, sebasam commented
### Summary

- User data added like req attribute from token, excuseme for that, i hadnt understand the context for the first change request jeje

2022-07-28 20:19 UTC, sebasam commented
### Summary

- Filename changed to user-authenticate.js
- bearer token logic added and user data received

Sorry, i hadnt undestand the problem context

2022-08-02 00:26 UTC, maxxCeballos approved these changes

2022-08-03 04:13 UTC, merged