Feature/testimonios endpoint
alkemyTech/OT244-Server pull request #22
Opened 2022-07-25 19:57 UTC by martincaceres2

-Testimonials file was already created, generated the create function.
-Created testimonials routes and middleware files

2022-07-26 00:11 UTC, maxxCeballos requested changes

2022-07-26 00:11 UTC, maxxCeballos commented on routes/testimonials.js
> +router.post('/', bodyFields, fieldsValidation, createTestimonial);
Poner recordatorio para agregar middleware para validar administrador, ya que solo un administrador puede realizar esta accion.

2022-07-26 13:31 UTC, martincaceres2 commented on routes/testimonials.js
> +router.post('/', bodyFields, fieldsValidation, createTestimonial);
Listo

2022-07-27 02:02 UTC, maxxCeballos approved these changes

2022-07-27 13:24 UTC, merged