Feature/decodejwt middleware
alkemyTech/OT244-Server pull request #23
Opened 2022-07-25 20:36 UTC by martincaceres2

-No se agrego la parte de roles porque vi la grabación de la reunión del viernes (que no pude asistir) y entendí que se aclaro que todavía no trabajábamos con el tema de roles.

2022-07-25 20:42 UTC, martincaceres2 commented
No se por que agregue eso en el .example.env. Me acabo de dar cuenta. Cuando toque hacer las correcciones lo saco

2022-07-26 00:14 UTC, maxxCeballos requested changes

2022-07-26 00:14 UTC, maxxCeballos commented on middlewares/jwt-validation.js
> +    }
No es lo que se pide en el ticket, leer bien

2022-07-27 02:17 UTC, maxxCeballos approved these changes

2022-07-27 13:25 UTC, merged