added route auth/me to show the personal data to the user
alkemyTech/OT244-Server pull request #24
Opened 2022-07-27 18:58 UTC by JAFleitas

- Se creo el controller para brindar la informacion personal a cada usuario que solicite sus datos
- Se creo la ruta GET auth/me
- NOTA:  Se uso el middleware validateJWT que aun esta no esta mergeado a la rama principal por lo que esta comentado.

2022-07-28 01:49 UTC, maxxCeballos requested changes

2022-07-28 01:49 UTC, maxxCeballos commented on controllers/user.js
> +}
No es lo que se pide en el ticket, leer con detenimiento la tarea

2022-07-28 02:49 UTC, JAFleitas commented on controllers/user.js
> +}
Hola Maxi, si hoy cuando estabamos en la daily, pensé que estaba haciendo algo mal, fíjate si está bien ahí, lo que me pedía el ticket era que envié los datos del usuario obtenido por el token, uso el Middleware que creo Seba que verificar el token y yo solo envío esos datos.

2022-08-02 00:24 UTC, maxxCeballos approved these changes

2022-08-04 00:09 UTC, merged