Role model,migration and controller added
alkemyTech/OT244-Server pull request #3
Opened 2022-07-15 12:34 UTC by bluemountains88

2022-07-19 03:56 UTC, maxxCeballos requested changes

2022-07-19 03:56 UTC, maxxCeballos commented on models/role.js
> +  }, { timestamps:true},{
funciona esto? se probo? es necesario agregar el id?

2022-07-21 02:26 UTC, bluemountains88 commented on models/role.js
> +  }, { timestamps:true},{
Se removio el id, y se quitaron los campos de timestamps incluidos en el modelo.

2022-07-22 13:28 UTC, maxxCeballos approved these changes

2022-07-22 15:20 UTC, merged