Delete member endpoint implemented
alkemyTech/OT244-Server pull request #30
Opened 2022-07-30 20:22 UTC by bluemountains88

- Middleware to check if member exists

2022-08-02 00:41 UTC, maxxCeballos requested changes

2022-08-02 00:41 UTC, maxxCeballos commented on controllers/member.js
> +        res.status(201)
por que se cambia esta linea?

2022-08-02 00:41 UTC, maxxCeballos commented on controllers/member.js
> +        res.sendStatus(204);
Por que status 204?

2022-08-02 00:41 UTC, maxxCeballos commented on middlewares/checkExists.js
> +}
Este middleware es innecesario, se puede hacer todo en el controller con una sola query a la base de datos

2022-08-02 11:51 UTC, bluemountains88 commented on middlewares/checkExists.js
> +}
Lo plantie asi por lo que dijimos el viernes sobre FindOrCreate() y la responsabilidad unica.

2022-08-02 11:52 UTC, bluemountains88 commented on controllers/member.js
> +        res.sendStatus(204);
Porque no devuelve info, pero modifica el deletedAt ...  crei que era el mas descriptivo por el soft delete

2022-08-03 19:49 UTC, maxxCeballos approved these changes

2022-08-03 20:02 UTC, merged