endopoint-detalle-categoria
alkemyTech/OT244-Server pull request #31
Opened 2022-07-30 21:46 UTC by sebasam

### Summary

- controller getCategoryById added, but for error i used the res.status form because the error handler doesnt work yet, when it will be work correctly, i will change that content.
- I can find categories by id
- If category doesnt exist, return error 404

2022-08-02 00:42 UTC, maxxCeballos requested changes

2022-08-02 00:42 UTC, maxxCeballos commented on routes/categories.js
> +router.get("/:id", getCategoryById);
Un usuario administrador puede realizar esta accion.

2022-08-03 05:11 UTC, sebasam commented
- verifyAdmin added

2022-08-03 19:46 UTC, maxxCeballos approved these changes

2022-08-03 20:20 UTC, merged