get all members
alkemyTech/OT244-Server pull request #33
Opened 2022-07-30 23:24 UTC by sebasam

### Summary

- Controller and get route for getMembers updated.
- Pending error handler, the error handler in the app doesnt return errors and postman, it could be a problem a future.

2022-08-02 00:43 UTC, maxxCeballos requested changes

2022-08-02 00:43 UTC, maxxCeballos commented on routes/members.js
> +router.get("/", getMembers)
Un administrador puede realizar esta accion.

2022-08-03 04:59 UTC, sebasam commented
### Summary

- Function verifyAdmin added

2022-08-03 19:44 UTC, maxxCeballos approved these changes

2022-08-03 20:17 UTC, merged