Endpoint creacion slides
alkemyTech/OT244-Server pull request #34
Opened 2022-07-31 02:32 UTC by jfilippo06

Controlador
Ruta
Enviar imagen a aws S3 y registrar la dirección de imagen en BD

2022-08-02 20:58 UTC, maxxCeballos requested changes

2022-08-02 20:58 UTC, maxxCeballos commented on routes/slides.js
> +router.post('/', /* verifyAdmin, */ postSlides)
No esta implementado todavia el verifyAdmin?

2022-08-02 20:58 UTC, maxxCeballos commented on controllers/slides.js
> +        const uploadedImage = await s3.upload(params).promise()
Dijimos que esto todavia no estaba implementado

2022-08-02 22:24 UTC, jfilippo06 commented on routes/slides.js
> +router.post('/', /* verifyAdmin, */ postSlides)
Bueno si

2022-08-03 19:41 UTC, maxxCeballos approved these changes

2022-08-03 20:30 UTC, merged