endpoint-eliminar-novedades
alkemyTech/OT244-Server pull request #36
Opened 2022-07-31 03:56 UTC by sebasam

### Resumen

Maxi te lo escribo en español porque tuve varios inconvenientes:

1. Había un problema con la relación de las novedades con las categorias, debido a que el campo categoryId estaba comentado, no me dejaba realizar la respectiva búsqueda; el problema ocurre al momento de migrar la base de datos con el nuevo campo ya que primero se crea la tabla roles y posteriormente se crea la tabla news, impidiendo la migración ya que la tabla categories debe existir primero. 
2. Para solucionar el error me vi obligado a eliminar la migracion de news, hacer la migración para que se creara primero categories, restaurar el archivo y migrarlo nuevamente; al hacer eso, logré migrar la base de datos y realizar las respectivas pruebas.
3. el endpoint /news/:id busca la novedad y si no se encuentra o ya fue eliminada, arroja un error, encaso de que no la elimine, ejecuta el método para eliminarla.

Quedo pendiente y en la reunión del lunes charlamos ese tema del problema con la migración.

Gracias maxi y quedo atento

2022-08-02 00:52 UTC, maxxCeballos requested changes

2022-08-02 00:52 UTC, maxxCeballos commented on controllers/categories.js
> +      description
Remover los cambios de este archivo, no tienen que ver con el ticket.

2022-08-02 00:52 UTC, maxxCeballos commented on controllers/news.js
> +    res.sendStatus(204)
Por que status code 204?

2022-08-02 00:52 UTC, maxxCeballos commented on migrations/20220714020924-create-news.js
> -      */
Remover los cambios de este archivo, no tienen que ver con el ticket.

2022-08-02 00:52 UTC, maxxCeballos commented on models/news.js
> +    categoryId: DataTypes.INTEGER
Remover los cambios de este archivo, no tienen que ver con el ticket.

2022-08-02 00:52 UTC, maxxCeballos commented on routes/index.js
> +router.use('/categories', categoryRouter);
Remover los cambios de este archivo, no tienen que ver con el ticket.

2022-08-02 00:52 UTC, maxxCeballos commented on routes/news.js
> +router.delete("/:id", checkNew, deleteNew);
Un administrador puede realizar esta accion

2022-08-02 00:52 UTC, maxxCeballos commented on middlewares/checkExists.js
> +}
Este middleware es innecesario, se puede hacer todo en el controller con una sola consulta a la base de datos

2022-08-03 04:53 UTC, sebasam commented
### Summary

- All changes that not belong to ticket has been deleted, middleware deleted and it work in controller deleteNew

2022-08-03 19:40 UTC, maxxCeballos requested changes

2022-08-03 19:40 UTC, maxxCeballos commented on controllers/news.js
> +        })
Con una sola consulta a la base de datos se puede lograr

2022-08-04 15:28 UTC, sebasam commented
The code has been refactored 👍🏽 💯

2022-08-05 19:58 UTC, maxxCeballos approved these changes

2022-08-06 01:08 UTC, merged