added endpoint deleteCategoryById
alkemyTech/OT244-Server pull request #37
Opened 2022-07-31 13:04 UTC by JAFleitas

-Se agrego la ruta DELETE:/categories/:id

2022-08-02 00:49 UTC, maxxCeballos requested changes

2022-08-02 00:49 UTC, maxxCeballos commented on controllers/categories.js
> +    }
Con una sola query a la base de datos se puede realizar esta accion, no es necesario hacer dos consultas. Recordar que las operaciones I/O son las costosas

2022-08-02 00:54 UTC, JAFleitas commented on controllers/categories.js
> +    }
Tenés razón Maxi gracias por el feedback en 1hora cuando vuelvo lo soluciono

2022-08-03 19:37 UTC, maxxCeballos approved these changes

2022-08-04 00:45 UTC, merged