Feature/update activities
alkemyTech/OT244-Server pull request #38
Opened 2022-07-31 13:41 UTC by JAFleitas

- Se agrego endpoint PUT:/activities/:id para que el administrador pueda actualizar las actividades por id 
-  Se crearon validaciones para controlar los cambios envaidos a la base de datos.

2022-08-02 20:54 UTC, maxxCeballos requested changes

2022-08-02 20:54 UTC, maxxCeballos commented on middlewares/validationBody.js
> +];
no se puede reutilizar el que esta creado para el post?

2022-08-02 20:54 UTC, maxxCeballos commented on controllers/activities.js
> +        });
Hacer una sola consulta a la base de datos

2022-08-02 20:54 UTC, maxxCeballos commented on controllers/activities.js
> +        return res.status(201).json(updatedActivity);
Status code 201 es cuando se crea un recurso, utilizar 200

2022-08-02 21:00 UTC, JAFleitas commented on controllers/activities.js
> +        });
Tengo que devolver la data, por eso lo hago dos veces, si pongo un instanceModel.set(....) y despues uso el instanceModel.save() es lo mismo creo o no ?

2022-08-02 21:56 UTC, JAFleitas commented on middlewares/validationBody.js
> +];
En este caso, los campos a validar son opcionales, y al crear la actividad se pide name y content de forma obligatoria, pero me fijo si se puede modularizar de alguna forma 👍

2022-08-02 22:55 UTC, JAFleitas commented on controllers/activities.js
> +        return res.status(201).json(updatedActivity);
Gracias si ya lo cambie

2022-08-05 19:55 UTC, maxxCeballos approved these changes

2022-08-05 19:55 UTC, maxxCeballos commented on middlewares/validationBody.js
> +];
Si son obligatorios al crear tiene sentido que sean obligatorios al actualizar tambien.
Sino podemos borrar info que en el post pediamos de forma obligatoria.

2022-08-06 01:10 UTC, merged