Feature/endpoint update news
alkemyTech/OT244-Server pull request #39
Opened 2022-08-01 13:19 UTC by martincaceres2

2022-08-02 20:47 UTC, maxxCeballos requested changes

2022-08-02 20:47 UTC, maxxCeballos commented on routes/news.js
> +router.put('/:id', /* verifyAdmin */  bodyUpdateNews, validationResult, updateNews);
No esta implementado todavia el verifyAdmin para agregar en la ruta?

2022-08-02 20:47 UTC, maxxCeballos commented on middlewares/validationBody.js
> +]
No se puede reutilizar el mismo de news que esta implementado?

2022-08-02 20:47 UTC, maxxCeballos commented on controllers/news.js
> +      return res.status(201).json({
Status code apropiado es 200, 201 es cuando se crea un recurso

2022-08-03 19:32 UTC, maxxCeballos requested changes

2022-08-03 19:32 UTC, maxxCeballos commented on controllers/news.js
> +      });
Martin disculpa, no me habia dado cuenta pero el ticket pide devolver la new con los datos actualizados

2022-08-03 19:36 UTC, martincaceres2 commented on controllers/news.js
> +      });
Yo tampoco me di cuenta. No pasa nada Maxi. Lo dejo con las dos queries como estaba entonces hasta que lo veamos

2022-08-05 19:59 UTC, maxxCeballos approved these changes

2022-08-06 00:54 UTC, merged