Activities controller, model and migration added
alkemyTech/OT244-Server pull request #4
Opened 2022-07-15 14:24 UTC by bluemountains88

2022-07-19 04:00 UTC, maxxCeballos requested changes

2022-07-19 04:00 UTC, maxxCeballos commented on migrations/20220715140317-create-activities.js
> +      }
falta atributo deletedAt

2022-07-19 04:00 UTC, maxxCeballos commented on models/activities.js
> +    },
Es necesario agregar el id?

2022-07-21 02:08 UTC, bluemountains88 commented on migrations/20220715140317-create-activities.js
> +      }
Atributo agreagado

2022-07-21 02:14 UTC, bluemountains88 commented on models/activities.js
> +    },
Quite el id del modelo

2022-07-22 13:19 UTC, maxxCeballos approved these changes

2022-07-22 19:30 UTC, merged