Endpoint/update testimonios
alkemyTech/OT244-Server pull request #41
Opened 2022-08-01 21:10 UTC by mar-romero

Tarea realizada, actualización de testimonios y devuelve en un JSON sus actualizaciones

2022-08-02 20:40 UTC, maxxCeballos requested changes

2022-08-02 20:40 UTC, maxxCeballos commented on routes/auth.js
> +router.post("/register",  /*verifyAdmin,*/bodyRegister, validationResult, createUser);
Esto no corresponde con el ticket

2022-08-02 20:40 UTC, maxxCeballos commented on routes/testimonials.js
> +router.put('/:id',/* verifyAdmin */ testimonials, validationResult, putByIdTestimonial)
No esta todavia el verifyAdmin que no se agrega?

2022-08-02 20:40 UTC, maxxCeballos commented on controllers/testimonial.js
> +    });
Hacer una sola consulta a la base de datos

2022-08-02 20:40 UTC, maxxCeballos commented on controllers/testimonial.js
> +    return res.status(201).json(testimonial);
El status 201 es cuando se crea un recurso, en este caso seria 200

2022-08-05 20:04 UTC, maxxCeballos requested changes

2022-08-05 20:04 UTC, maxxCeballos commented on controllers/testimonial.js
> +    return res.status(200).json(testimonial);
Se esta devolviendo el testimonio que se recupero antes de actualizar, el que se devuelve es el que ya esta actualizado.

2022-08-05 20:05 UTC, maxxCeballos commented
Corregir todos los cambios que se marcaron por favor

2022-08-08 18:32 UTC, mar-romero commented on routes/auth.js
> +router.post("/register",  /*verifyAdmin,*/bodyRegister, validationResult, createUser);
si me confundi de seccion, ya se volvio, como estaba

2022-08-08 23:57 UTC, mar-romero commented
Maxi, ya se realizaron todos los cambios solicitados

2022-08-12 00:15 UTC, maxxCeballos approved these changes

2022-08-12 01:46 UTC, merged