Endpoint detalles slides
alkemyTech/OT244-Server pull request #45
Opened 2022-08-06 19:51 UTC by jfilippo06

Solicitar slides
Rutas, controlador, servicio y capa de datos

2022-08-08 23:11 UTC, maxxCeballos requested changes

2022-08-08 23:11 UTC, maxxCeballos commented on controllers/slides.js
> +    else res.status(200).json(data)
Que sucede si ocurre un error? no se esta catcheando

2022-08-08 23:11 UTC, maxxCeballos commented on controllers/slides.js
> +    const data = await getId(req)
no pasar el objeto req por parametro

2022-08-08 23:11 UTC, maxxCeballos commented on DAL/slides.js
> +const allId =  async (id) => {
allId no es un nombre descriptivo, usar nombres que representen lo que se esta haciendo

2022-08-12 00:20 UTC, maxxCeballos requested changes

2022-08-12 00:20 UTC, maxxCeballos commented on DAL/slides.js
> +const findAllSlidesById =  async (id) => {
Si se hace un findOne significa que se va a recuperar un solo slide, que el nombre sea findAll.. es un poco contradictorio, pensar bien los nombres, es importante porque le da mas legibilidad a cualquier persona que tenga que leer el codigo

2022-08-12 00:20 UTC, maxxCeballos commented on DAL/slides.js
> +    const category = await Slides.findOne({
la variable se llama category y se estan recuperando slides..

2022-08-12 00:35 UTC, jfilippo06 commented on DAL/slides.js
> +const findAllSlidesById =  async (id) => {
Si, es verdad

2022-08-12 00:36 UTC, jfilippo06 commented on DAL/slides.js
> +    const category = await Slides.findOne({
Listo ya lo cambie

2022-08-17 03:21 UTC, maxxCeballos approved these changes

2022-08-17 17:35 UTC, merged