Feature/Model and migration of the contacts table created
alkemyTech/OT244-Server pull request #46
Opened 2022-08-07 00:05 UTC by JAFleitas

2022-08-08 23:19 UTC, maxxCeballos requested changes

2022-08-08 23:19 UTC, maxxCeballos commented on migrations/20220806235253-create-contacts.js
> +        allowNull: false,
Este campo deber ser `allowNull : true` ya que al crear un registro se inicia como null.

2022-08-08 23:19 UTC, maxxCeballos commented on models/contacts.js
> +    phone: DataTypes.INTEGER,
Corroborar este tipo de dato, nose si el intervalo de numeros que incluye integer alcanza para contener numeros de telefonos porque son numeros muy altos, de muchos digitos

2022-08-12 23:32 UTC, JAFleitas commented on migrations/20220806235253-create-contacts.js
> +        allowNull: false,
Perfecto max se me paso , ya esta solucionado

2022-08-12 23:32 UTC, JAFleitas commented on models/contacts.js
> +    phone: DataTypes.INTEGER,
Solucionado Max gracias por el feedback

2022-08-17 03:23 UTC, maxxCeballos approved these changes

2022-08-17 17:35 UTC, merged