comments updated by id
alkemyTech/OT244-Server pull request #48
Opened 2022-08-07 03:47 UTC by sebasam

### Summary

- Comments can be updating by id

2022-08-08 23:29 UTC, maxxCeballos requested changes

2022-08-08 23:29 UTC, maxxCeballos commented on controllers/comments.js
> +        const data = await putCommentService( req, res )
no pasar el objeto req, res por parametro.

2022-08-08 23:29 UTC, maxxCeballos commented
El ticket tambien especifica que: Solamente podrán editar un comentario el usuario que lo realizó o un administrador

2022-08-09 00:58 UTC, sebasam commented
- req and res parameters removed, verifyAdmin added

2022-08-12 00:28 UTC, maxxCeballos requested changes

2022-08-12 00:28 UTC, maxxCeballos commented on routes/comments.js
> +router.put("/:id", verifyAdmin, putComment)
Seba leer bien el ticket, dice que lo pueden actualizar los administradores O el usuario que lo creo. Hay un middleware de Ownership para eso

2022-08-12 00:28 UTC, maxxCeballos commented on services/comments.js
> +        return res.status(404).json({
el objeto `res` no esta en el scope de la funcion para poder invocarlo

2022-08-14 19:48 UTC, sebasam commented
Maxi ya los cambios están, disculpame por los errors

2022-08-17 03:25 UTC, maxxCeballos approved these changes

2022-08-17 17:43 UTC, merged