crear contacto
alkemyTech/OT244-Server pull request #49
Opened 2022-08-07 06:10 UTC by sebasam

- POST /contacts ya puede ser creado un contacto, si el email no existe

2022-08-08 23:34 UTC, maxxCeballos requested changes

2022-08-08 23:34 UTC, maxxCeballos commented on routes/contacts.js
> +router.post("/", validationResult, contacts, addContact)
esta bien el orden de los middlewares?

2022-08-08 23:34 UTC, maxxCeballos commented on controllers/contacts.js
> +        const data = await createNewContact(req, res)
no pasar objetos req, res por parametro

2022-08-09 00:50 UTC, sebasam commented
- Changes resolved maxid, im pending :)

2022-08-12 00:31 UTC, maxxCeballos approved these changes

2022-08-12 01:53 UTC, merged