Create model migration controller database users
alkemyTech/OT244-Server pull request #5
Opened 2022-07-15 18:28 UTC by sebasam

### Summary

- Model user added by sequelize-cli.
- Migration user added by sequelize-cli.
- Controllers folder created and userControllers.js file added.

2022-07-19 04:02 UTC, maxxCeballos commented
No usar la notacion camelCase para nombrar el archivo controlador, utilizar user.controller.js o user.js dentro de la carpeta controller ya define que es un controller.

2022-07-19 04:09 UTC, maxxCeballos requested changes

2022-07-19 04:09 UTC, maxxCeballos commented on migrations/20200921211634-create-user.js
> +
remover este espacio que se agrega

2022-07-19 04:09 UTC, maxxCeballos commented on migrations/20220715181113-create-user.js
> +module.exports = {
para que se hace de nuevo otro migration?

2022-07-19 04:09 UTC, maxxCeballos commented on migrations/20200921211634-create-user.js
> +        notNull: true,
existe la propiedad notNull?

2022-07-19 05:25 UTC, sebasam commented
### Summary

1.  Controller filename has been fixed.
2.  Duplicate migration deleted and notNull chaned to allowNull.

2022-07-20 16:54 UTC, maxxCeballos requested changes

2022-07-20 16:54 UTC, maxxCeballos commented on migrations/20220715181113-create-user.js
> +      LastName: {
usar minusculas como primera letra de atributo

2022-07-20 16:54 UTC, maxxCeballos commented on models/user.js
> +    LastName: DataTypes.STRING,
usar minusculas como primera letra de atributo

2022-07-20 19:38 UTC, sebasam commented
### Summary

Capital letter from LastName has been removed for lastName, sorry for that issue

2022-07-22 13:21 UTC, maxxCeballos approved these changes

2022-07-22 19:16 UTC, merged