Feature/comments model migration
alkemyTech/OT244-Server pull request #57
Opened 2022-08-08 20:12 UTC by martincaceres2

2022-08-08 23:47 UTC, maxxCeballos requested changes

2022-08-08 23:47 UTC, maxxCeballos commented on migrations/20220805133527-create-comment.js
> +        allowNull: false,
Esto deberia ser `allowNull: true` ya que cuando se crea el registro se inicializa en null

2022-08-09 23:58 UTC, martincaceres2 commented on migrations/20220805133527-create-comment.js
> +        allowNull: false,
Arreglado

2022-08-12 00:47 UTC, maxxCeballos approved these changes

2022-08-12 01:22 UTC, merged