model, migration, controllers folder and empty file added
alkemyTech/OT244-Server pull request #6
Opened 2022-07-15 18:44 UTC by sebasam

### Summary

- Model member added.
-  Migration member added.
- Controllers folder and empty file added.

2022-07-19 04:10 UTC, maxxCeballos commented
No usar la notacion camelCase para nombrar el archivo controlador, utilizar member.controller.js o member.js dentro de la carpeta controller ya define que es un controller.

2022-07-19 04:13 UTC, maxxCeballos requested changes

2022-07-19 04:13 UTC, maxxCeballos commented on models/member.js
> +    deletedAt: DataTypes.DATE
es necesario agregar el deletedAt de nuevo aca?

2022-07-19 05:26 UTC, sebasam commented
### Summary

1. Controller filename has been fixed.
2. deleteAt has been deleted from models/member

2022-07-20 16:48 UTC, maxxCeballos approved these changes

2022-07-20 21:08 UTC, merged