Crear seed de usuarios
alkemyTech/OT244-Server pull request #7
Opened 2022-07-15 20:06 UTC by jfilippo06

Semilla de usuarios creada
10 usuarios administradores
10 usuarios estándar
+ añadidos en archivo .README

2022-07-19 23:10 UTC, maxxCeballos requested changes

2022-07-19 23:10 UTC, maxxCeballos commented on seeders/20220714223154-user.js
> +      password: '1234',
el password debe estar encriptado del mismo modo que se encripta cuando re registras. Ver PR de registro de usuario, o hablar con Gonza Fleitas.

2022-07-20 02:37 UTC, jfilippo06 reviewed
Contraseñas encriptadas con bcrypt
Añadido variables de entornos para proteger los saltos de bcrypt y contraseñas
Variables de entorno en .env.example

2022-07-20 16:49 UTC, maxxCeballos approved these changes

2022-07-20 21:26 UTC, merged