Feature/create model migration controller testimonials
alkemyTech/OT244-Server pull request #8
Opened 2022-07-15 23:19 UTC by JAFleitas

Added model, migration and Testimonial controller

2022-07-19 23:14 UTC, maxxCeballos requested changes

2022-07-19 23:14 UTC, maxxCeballos commented on models/testimonial.js
> +      deletedAt: "destroyTime",
es necesario colocar el deletedAt aca cuando ya esta declarado al crear la tabla?

2022-07-19 23:14 UTC, maxxCeballos commented on models/testimonial.js
> +      },
hace falta colocar el id aca?

2022-07-20 21:53 UTC, JAFleitas commented on models/testimonial.js
> +      deletedAt: "destroyTime",
Maxi gracias por el feedback, respondiendo a la pregunta , no es necesario, revice la doc y lo quite del archivo. Saludos !

2022-07-20 21:53 UTC, JAFleitas commented on models/testimonial.js
> +      },
Maxi gracias por el feedback, respondiendo a la pregunta , no es necesario, revice la doc y lo quite del archivo. Saludos !

2022-07-22 13:26 UTC, maxxCeballos approved these changes

2022-07-22 19:30 UTC, merged